name: smart_transit
description: "A complete Flutter Front-End only mobile application for Smart Transit."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  intl: ^0.20.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  uuid: ^4.2.1
  collection: ^1.18.0
  geolocator: ^10.1.0
  dio: ^5.9.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

